// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNytH_JQn0sWDkr1CmMffyPNFxH-V1Wfo',
    appId: '1:140879282910:web:e1a6c34fa8a1ebdca6384f',
    messagingSenderId: '140879282910',
    projectId: 'd-italia-13fb9',
    authDomain: 'd-italia-13fb9.firebaseapp.com',
    databaseURL: 'https://d-italia-13fb9-default-rtdb.firebaseio.com',
    storageBucket: 'd-italia-13fb9.appspot.com',
    measurementId: 'G-7FV6YZ3QTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu-uHIcpxkfmhS5bm53UGBGcBQb6x1qWE',
    appId: '1:140879282910:android:32b752b49243bd67a6384f',
    messagingSenderId: '140879282910',
    projectId: 'd-italia-13fb9',
    databaseURL: 'https://d-italia-13fb9-default-rtdb.firebaseio.com',
    storageBucket: 'd-italia-13fb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_b3Ng6Ru6tdZkYhZvc1NhWzBLMyhnWg',
    appId: '1:140879282910:ios:d0ec63fa26281d68a6384f',
    messagingSenderId: '140879282910',
    projectId: 'd-italia-13fb9',
    databaseURL: 'https://d-italia-13fb9-default-rtdb.firebaseio.com',
    storageBucket: 'd-italia-13fb9.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_b3Ng6Ru6tdZkYhZvc1NhWzBLMyhnWg',
    appId: '1:140879282910:ios:dcc8ffd767114a9fa6384f',
    messagingSenderId: '140879282910',
    projectId: 'd-italia-13fb9',
    databaseURL: 'https://d-italia-13fb9-default-rtdb.firebaseio.com',
    storageBucket: 'd-italia-13fb9.appspot.com',
    iosBundleId: 'com.int2.flutterEcommerceTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNytH_JQn0sWDkr1CmMffyPNFxH-V1Wfo',
    appId: '1:140879282910:web:e89f00e9ffd56329a6384f',
    messagingSenderId: '140879282910',
    projectId: 'd-italia-13fb9',
    authDomain: 'd-italia-13fb9.firebaseapp.com',
    databaseURL: 'https://d-italia-13fb9-default-rtdb.firebaseio.com',
    storageBucket: 'd-italia-13fb9.appspot.com',
    measurementId: 'G-ZXRYLM21MW',
  );
}
